### ISSUE TITLE
Need a draft commarch team proposal 

### ISSUE THREAD

**Issue by ritjoe** [PatrickGormley/hfoss#3]
A week ago, you were asked to identify at least two projects to consider analyzing for the community architecture assignment. Please provide these in the form of a draft team proposal.

There are many acceptable ways to communicate this to your instructor, but submitting a commit in a drafts folder on a feature branch of this repository would be acceptable.

**Comment by PatrickGormley** [comment]
https://github.com/godotengine/godot - Open source game engine that. Looks to have good documentation. Also has links to several open source games, which could be a nice addition to look at.
